server:
  port: 8888
  context-path: /emp
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: hr
    password: hr
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity
